In [1]:
import numpy as np
data = []
baris = 0
kolom = 6
bobot = []

In [2]:
def deklarasi_ukuranData():
    global data
    global alternatif
    global baris
    global kolom
    #deklarasi matrix sementara
    baris = int(input("Masukkan Jumlah Baris Data : "))
    data = np.zeros((baris, kolom), dtype=object)
    print("Data Sementara : ")
    print(data)
    print("Ukuran Data : ", data.shape)

In [4]:
def input_data():
    global data
    global baris
    global kolom
    #input data ke matrix
    for x in range(baris):
        for y in range(kolom):
            if y == 0:
                print("Masukkan Nomor ID Peserta ", x+1)
                a = str(input())
                data[x][y] = a
            elif y == 1:
                print("Masukkan Nilai Tes Pengetahuan Sistem Informasi")
                a = float(input())
                data[x][y] = a
            elif y == 2:
                print("Masukkan Nilai Praktik Instalasi Jaringan")
                a = float(input())
                data[x][y] = a
            elif y == 3:
                print("Masukkan Nilai Tes Kepribadian")
                a = float(input())
                data[x][y] = a
            elif y == 4:
                print("Masukkan Nilai Tes Pengetahuan Agama")
                a = float(input())
                data[x][y] = a
#     main()

In [6]:
def normalisasi_data():
    #Mencari ukuran matrix
    baris, kolom = data.shape
    print("Jumlah Baris : ", baris)
    print("Jumlah Kolom : ", kolom)

    #Mencari nilai maksimum setiap kolom/kriteria
    maksimum = np.amax(data, axis=0)
    minimum = np.amin(data, axis=0)
    print("\nNilai Maksimum Setiap Kolom : ", maksimum)
    print("Banyaknya Nilai Matrix Maksimum : ", maksimum.shape)
    print("\nNilai Minimum Setiap Kolom : ", minimum)
    print("Banyaknya Nilai Matrix Minimum : ", minimum.shape)
    maksimum1 = maksimum[1]
    maksimum2 = maksimum[2]
    maksimum3 = maksimum[3]
    maksimum4 = maksimum[4]
    print("Nilai Maksimum Kriteria 1 : ", maksimum1)
    print("Nilai Maksimum Kriteria 2 : ", maksimum2)
    print("Nilai Maksimum Kriteria 3 : ", maksimum3)
    print("Nilai Maksimum Kriteria 4 : ", maksimum4)

    #Tahapan Normalisasi
    for y in range(kolom):
        if y == 0 or y == 5:
            continue
        for x in range(baris):
            if y == 1:
                data[x][y] = data[x][y]/maksimum1
            elif y == 2:
                data[x][y] = data[x][y]/maksimum2
            elif y == 3:
                data[x][y] = data[x][y]/maksimum3
            elif y == 4:
                data[x][y] = data[x][y]/maksimum4

    #Hasil Normalisasi
    print("\nData Hasil Normalisasi : ")
    print(data)

In [8]:
def input_bobot():
    global bobot
    global kolom
    bobot = np.zeros(kolom)
    print("Bobot Penilaian Dalam Persen 100% = 1")
    for y in range(kolom):
        if y == 0 or y == 5:
            bobot[y] = 0
        elif y == 1:
            print("Masukan Nilai Bobot Tes Pengetahuan Sistem Informasi")
            a = float(input())
            bobot[y] = a
        elif y == 2:
            print("Masukan Nilai Bobot Praktek Instalasi Jaringan")
            a = float(input())
            bobot[y] = a
        elif y == 3:
            print("Masukan Nilai Bobot Tes Kepribadian")
            a = float(input())
            bobot[y] = a
        elif y == 4:
            print("Masukan Nilai Bobot Tes Pengetahuan Agama")
            a = float(input())
            bobot[y] = a
    print("Nilai Bobot Penilaian :")
    print(bobot)

In [10]:
def SAW():
    global data
    global baris
    global kolom
    
    #Proses Perkalian
    for y in range(kolom):
        if y == 0:
            continue
        for x in range(baris):
            data[x][y] = data[x][y]*bobot[y]
    print("\nHasil Perkalian Dengan Bobot : ")
    print(data)
    
    #Proses Perankingan
    for a in range(baris):
        hasil = 0
        for b in range(kolom-1):
            if b == 0:
                continue
            hasil = hasil + data[a][b]
        data[a][kolom-1]=hasil
    print("\nHasil Penjumlahan : ")
    print(data)
    
    #Hasil Perangkingan
    print("\nHasil Akhir Perangkingan")
    hasil = data[data[:, 5].argsort()][::-1]
    print("Nomor Peserta : ", hasil[0][0])
    print("Nilai Akhir Peserta : ", hasil[0][5])

In [12]:
def menu():
    print("\nPilih Operasi : ")
    print("1. Deklarasi Banyak Data")
    print("2. Input Data")
    print("3. Kosongkan Data")
    print("4. Lihat Data")
    print("5. Normalisasi Data")
    print("6. Input Bobot Kriteria")
    print("7. Perangkingan dengan SAW")

In [13]:
def main():
    menu()
    global data
    pilihan = int(input("Masukkan Pilihan Operasi : "))
    if pilihan == 1:
        deklarasi_ukuranData()
        main()
    elif pilihan == 2:
        input_data()
        main()
    elif pilihan == 3:
        data = np.zeros((2, 2))
        main()
    elif pilihan == 4:
        print("Data Saat Ini : ")
        print(data)
        main()
    elif pilihan == 5:
        normalisasi_data()
        main()
    elif pilihan == 6:
        input_bobot()
        main()
    elif pilihan == 7:
        SAW()
        main()
    else :
        print("Pilihan Tidak Tersedia")

In [14]:
main()


Pilih Operasi : 
1. Deklarasi Banyak Data
2. Input Data
3. Kosongkan Data
4. Lihat Data
5. Normalisasi Data
6. Input Bobot Kriteria
7. Perangkingan dengan SAW
Masukkan Pilihan Operasi : 1
Masukkan Jumlah Baris Data : 6
Data Sementara : 
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
Ukuran Data :  (6, 6)

Pilih Operasi : 
1. Deklarasi Banyak Data
2. Input Data
3. Kosongkan Data
4. Lihat Data
5. Normalisasi Data
6. Input Bobot Kriteria
7. Perangkingan dengan SAW
Masukkan Pilihan Operasi : 2
Masukkan Nomor ID Peserta  1
Indra
Masukkan Nilai Tes Pengetahuan Sistem Informasi
70
Masukkan Nilai Praktik Instalasi Jaringan
50
Masukkan Nilai Tes Kepribadian
80
Masukkan Nilai Tes Pengetahuan Agama
60
Masukkan Nomor ID Peserta  2
Roni
Masukkan Nilai Tes Pengetahuan Sistem Informasi
50
Masukkan Nilai Praktik Instalasi Jaringan
60
Masukkan Nilai Tes Kepribadian
82
Masukkan Nilai Tes Pengetahuan Agama
70
Masukkan Nomor ID Peserta  3
Putri
Masukkan Nilai T